apiVersion: v1
kind: Service
metadata:
  name: seatunnel-master-external
  # namespace: seatunnel
  labels:
    app: seatunnel-master
spec:
  type: NodePort
  selector:
    app: seatunnel-master
  ports:
    - name: rest-api
      port: 5801
      targetPort: 5801
      nodePort: 30001
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30002