apiVersion: v1
kind: Service
metadata:
  name: seatunnel-web
  namespace: seatunnel
  labels:
    app: seatunnel-web
spec:
  selector:
    app: seatunnel-web
  ports:
    - name: seatunnel-web
      port: 8801
      targetPort: 8801
      nodePort: 30003
  type: NodePort