apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-worker
  namespace: seatunnel
  labels:
    app: seatunnel-worker
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-config"
spec:
  serviceName: "seatunnel-worker"
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-worker
  template:
    metadata:
      labels:
        app: seatunnel-worker
    spec:
      containers:
        - name: seatunnel-worker
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5802
              name: hazelcast
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/seatunnel/bin/seatunnel-cluster.sh -r worker -DJvmOption=-Xms1G -Xmx1G"
          resources:
            requests:
              cpu: "1"
              memory: 1G
            limits:
              cpu: "1"
              memory: 1G
          volumeMounts:
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config
            - name: seatunnel-worker-pvc
              mountPath: /mnt/seatunnel
            - name: seatunnel-worker-pvc
              mountPath: /opt/seatunnel/connectors
            - name: seatunnel-worker-pvc
              mountPath: /opt/seatunnel/lib
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
        - name: seatunnel-worker-pvc
          persistentVolumeClaim:
            claimName: seatunnel-worker-pvc
