apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-worker
  namespace: seatunnel
  labels:
    app: seatunnel-worker
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-config"
spec:
  serviceName: "seatunnel-worker"
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-worker
  template:
    metadata:
      labels:
        app: seatunnel-worker
    spec:
      initContainers:
        - name: init-volume
          image: busybox
          command: [ "sh", "-c", "mkdir -p /mnt/data/seatunnel /mnt/data/connectors /mnt/data/lib" ]
          volumeMounts:
            - name: seatunnel-worker-pvc
              mountPath: /mnt/data
      containers:
        - name: seatunnel-worker
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5802
              name: hazelcast
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/seatunnel/bin/seatunnel-cluster.sh -r worker -DJvmOption=-Xms1G -Xmx1G"
          resources:
            requests:
              cpu: "1"
              memory: 1G
            limits:
              cpu: "1"
              memory: 1G
          volumeMounts:
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-worker.yaml"
              subPath: hazelcast-worker.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-client.yaml"
              subPath: hazelcast-client.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/seatunnel.yaml"
              subPath: seatunnel.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/log4j2.properties"
              subPath: log4j2.properties

            - name: seatunnel-worker-pvc
              mountPath: /mnt/seatunnel
              subPath: seatunnel
            - name: seatunnel-worker-pvc
              mountPath: /opt/seatunnel/connectors
              subPath: connectors
            - name: seatunnel-worker-pvc
              mountPath: /opt/seatunnel/lib
              subPath: lib
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
        - name: seatunnel-worker-pvc
          persistentVolumeClaim:
            claimName: seatunnel-worker-pvc
