apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seatunnel-hpa-worker
  namespace: seatunnel-cluster
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: seatunnel-worker

