apiVersion: v1
kind: Service
metadata:
  name: seatunnel-worker
  namespace: seatunnel-cluster
spec:
  selector:
    app: seatunnel-worker
  ports:
    - name: internal-communication
      port: 5802
      targetPort: 5802
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-worker
  namespace: seatunnel-cluster
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-config"
spec:
  serviceName: "seatunnel-worker"
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-worker
  template:
    metadata:
      labels:
        app: seatunnel-worker
    spec:
      containers:
        - name: seatunnel-worker
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5802
              name: hazelcast
          command:
            - /bin/sh
            - -c
            - >
              /opt/seatunnel/bin/seatunnel-cluster.sh -r worker
          # env:
          #   - name: JvmOption
          #     value: "-Xms1G -Xmx2G"
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: "1"
              memory: 2G
          volumeMounts:
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-worker.yaml"
              subPath: hazelcast-worker.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-client.yaml"
              subPath: hazelcast-client.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/seatunnel.yaml"
              subPath: seatunnel.yaml
            - name: seatunnel-pvc
              mountPath: /mnt/seatunnel
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
        - name: seatunnel-pvc
          persistentVolumeClaim:
            claimName: seatunnel-pvc