apiVersion: v1
kind: Service
metadata:
  name: seatunnel-master
spec:
  type: NodePort
  selector:
    app: seatunnel-master
  ports:
    - name: rest-api
      port: 5801
      targetPort: 5801
      nodePort: 30001
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-master
  annotations:
    configmap.reloader.stakater.com/reload: "hazelcast-master,hazelcast-client,seatunnelmap"
spec:
  serviceName: "seatunnel-master"
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-master
  template:
    metadata:
      labels:
        app: seatunnel-master
    spec:
      containers:
        - name: seatunnel-master
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5801
              name: client
            - containerPort: 8080
              name: ui
          command:
            - /bin/sh
            - -c
            - >
              /opt/seatunnel/bin/seatunnel-cluster.sh -r master
              # -Xms1G -Xmx2G
              # for above Java 8
              --add-modules java.se
              --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
              --add-opens java.base/java.lang=ALL-UNNAMED
              --add-opens java.base/sun.nio.ch=ALL-UNNAMED
              --add-opens java.management/sun.management=ALL-UNNAMED
              --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          volumeMounts:
            - mountPath: "/opt/seatunnel/config/hazelcast-master.yaml"
              name: hazelcast-master
              subPath: hazelcast-master.yaml
            - mountPath: "/opt/seatunnel/config/hazelcast-client.yaml"
              name: hazelcast-client
              subPath: hazelcast-client.yaml
            - mountPath: "/opt/seatunnel/config/seatunnel.yaml"
              name: seatunnelmap
              subPath: seatunnel.yaml
            - name: seatunnel-pvc
              mountPath: /mnt/seatunnel
      volumes:
        - name: hazelcast-master
          configMap:
            name: hazelcast-master
        - name: hazelcast-client
          configMap:
            name: hazelcast-client
        - name: seatunnelmap
          configMap:
            name: seatunnelmap
        - name: seatunnel-pvc
          persistentVolumeClaim:
            claimName: seatunnel-pvc