apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatunnel-web
  namespace: seatunnel-web
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-web-config"
  labels:
    app: seatunnel-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-web
  template:
    metadata:
      labels:
        app: seatunnel-web
    spec:
      containers:
        - name: seatunnel-web
          image: amol64546/seatunnel-web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8801
              name: web-ui
          env:
            - name: SEATUNNEL_HOME
              value: /app
          command: ["sh", "-c"]
          args:
            - >
              sh bin/seatunnel-backend-daemon.sh start &&
              tail -f /dev/null
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: seatunnel-web-config
              mountPath: /app/conf
            - name: seatunnel-web-pvc
              mountPath: /app/libs
      volumes:
        - name: seatunnel-web-config
          configMap:
            name: seatunnel-web-config
        - name: seatunnel-web-pvc
          persistentVolumeClaim:
            claimName: seatunnel-web-pvc
