apiVersion: v1
kind: Service
metadata:
  name: seatunnel-master
  namespace: seatunnel
  labels:
    app: seatunnel-master
spec:
  type: NodePort
  selector:
    app: seatunnel-master
  ports:
    - name: rest-api
      port: 5801
      targetPort: 5801
      nodePort: 30001
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-master
  namespace: seatunnel
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-config"
spec:
  serviceName: "seatunnel-master"
  selector:
    matchLabels:
      app: seatunnel-master
  template:
    metadata:
      labels:
        app: seatunnel-master
    spec:
      containers:
        - name: seatunnel-master
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5801
              name: client
            - containerPort: 8080
              name: ui
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/seatunnel/bin/seatunnel-cluster.sh -r master -DJvmOption=-Xms1G -Xmx1G"
          resources:
            requests:
              cpu: "1"
              memory: 1G
            limits:
              cpu: "1"
              memory: 1G
          volumeMounts:
            - name: seatunnel-config
              mountPath: /opt/seatunnel/config
            - name: seatunnel-master-pvc
              mountPath: /mnt/seatunnel
            - name: seatunnel-master-pvc
              mountPath: /opt/seatunnel/connectors
            - name: seatunnel-master-pvc
              mountPath: /opt/seatunnel/lib
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
        - name: seatunnel-master-pvc
          persistentVolumeClaim:
            claimName: seatunnel-master-pvc
