apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-master
  namespace: seatunnel
  labels:
    app: seatunnel-master
  annotations:
    configmap.reloader.stakater.com/reload: "seatunnel-config"
spec:
  serviceName: "seatunnel-master"
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-master
  template:
    metadata:
      labels:
        app: seatunnel-master
    spec:
      containers:
        - name: seatunnel-master
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5801
              name: client
            - containerPort: 8080
              name: ui
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/seatunnel/bin/seatunnel-cluster.sh -r master -DJvmOption=-Xms1G -Xmx1G"
          resources:
            requests:
              cpu: "1"
              memory: 1G
            limits:
              cpu: "1"
              memory: 1G
          volumeMounts:
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-master.yaml"
              subPath: hazelcast-master.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/hazelcast-client.yaml"
              subPath: hazelcast-client.yaml
            - name: seatunnel-config
              mountPath: "/opt/seatunnel/config/seatunnel.yaml"
              subPath: seatunnel.yaml
            - name: seatunnel-master-pvc
              mountPath: /mnt/seatunnel
            - name: seatunnel-connectors-pvc
              mountPath: /opt/seatunnel/connectors
            - name: seatunnel-lib-pvc
              mountPath: /opt/seatunnel/lib
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
        - name: seatunnel-master-pvc
          persistentVolumeClaim:
            claimName: seatunnel-master-pvc
        - name: seatunnel-connectors-pvc
          persistentVolumeClaim:
            claimName: seatunnel-connectors-pvc
        - name: seatunnel-lib-pvc
          persistentVolumeClaim:
            claimName: seatunnel-lib-pvc
