apiVersion: v1
kind: Service
metadata:
  name: seatunnel-worker
spec:
  selector:
    app: seatunnel-worker
  ports:
    - name: internal-communication
      port: 5802
      targetPort: 5802
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatunnel-worker
  annotations:
    configmap.reloader.stakater.com/reload: "hazelcast-worker,hazelcast-client,seatunnelmap"
spec:
  serviceName: "seatunnel-worker"
  replicas: 2
  selector:
    matchLabels:
      app: seatunnel-worker
  template:
    metadata:
      labels:
        app: seatunnel-worker
    spec:
      containers:
        - name: seatunnel-worker
          image: amol64546/seatunnel:2.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5802
              name: hazelcast
          command:
            - /bin/sh
            - -c
            - >
              /opt/seatunnel/bin/seatunnel-cluster.sh -r worker
              # -Xms1G -Xmx2G
              # for above Java 8
              --add-modules java.se
              --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
              --add-opens java.base/java.lang=ALL-UNNAMED
              --add-opens java.base/sun.nio.ch=ALL-UNNAMED
              --add-opens java.management/sun.management=ALL-UNNAMED
              --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          volumeMounts:
            - mountPath: "/opt/seatunnel/config/hazelcast-worker.yaml"
              name: hazelcast-worker
              subPath: hazelcast-worker.yaml
            - mountPath: "/opt/seatunnel/config/hazelcast-client.yaml"
              name: hazelcast-client
              subPath: hazelcast-client.yaml
            - mountPath: "/opt/seatunnel/config/seatunnel.yaml"
              name: seatunnelmap
              subPath: seatunnel.yaml
            - name: seatunnel-pvc
              mountPath: /mnt/seatunnel
      volumes:
        - name: hazelcast-worker
          configMap:
            name: hazelcast-worker
        - name: hazelcast-client
          configMap:
            name: hazelcast-client
        - name: seatunnelmap
          configMap:
            name: seatunnelmap
        - name: seatunnel-pvc
          persistentVolumeClaim:
            claimName: seatunnel-pvc